name: Install MinGW
  # You may pin to the exact commit or the version.
  # uses: egor-tensin/setup-mingw@84c781b557efd538dec66bde06988d81cd3138cf
  uses: egor-tensin/setup-mingw@v2
  with:
    # Target platform
    platform: # optional, default is x64
    # Install Cygwin packages
    cygwin: # optional, default is 0
    # Enable static linking workaround
    static: # optional, default is 1
    # Set up cc/c++ executables
    cc: # optional, default is 1
    # On Cygwin, replace executable symlinks with hardlinks
    hardlinks: # optional, default is 0
    # Specify mingw version; will fall back to package manager default if not supplied
    version: # optional, default is 
          

name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make every1
    # Specify mingw version; will fall back to package manager default if not supplied
    version: # optional, default is 
          
